import Vue from 'vue'
import Component from 'vue-class-component'

@Component
export default class Ex extends Vue {
  render() {
    return (
      <pre class="chroma code prettyprint prettyprinted">
        <code class='code-content'>
          <span class="p">{"{"}</span>{"\n"}{"  "}<span class="nt">&#34;compilerOptions&#34;</span><span class="p">:</span> <span class="p">{"{"}</span>{"\n"}{"    "}<span class="nt">&#34;lib&#34;</span><span class="p">:</span> <span class="p">[</span>{"\n"}{"      "}<span class="s2">&#34;dom&#34;</span><span class="p">,</span>{"\n"}{"      "}<span class="s2">&#34;es6&#34;</span>{"\n"}{"    "}<span class="p">],</span>{"\n"}{"    "}<span class="nt">&#34;target&#34;</span><span class="p">:</span> <span class="s2">&#34;es2017&#34;</span><span class="p">,</span>{"\n"}{"    "}<span class="nt">&#34;module&#34;</span><span class="p">:</span> <span class="s2">&#34;esnext&#34;</span><span class="p">,</span>{"\n"}{"    "}<span class="nt">&#34;moduleResolution&#34;</span><span class="p">:</span> <span class="s2">&#34;node&#34;</span><span class="p">,</span>{"\n"}{"    "}<span class="nt">&#34;jsx&#34;</span><span class="p">:</span> <span class="s2">&#34;preserve&#34;</span><span class="p">,</span>{"\n"}{"    "}<span class="nt">&#34;isolatedModules&#34;</span><span class="p">:</span> <span class="kc">false</span><span class="p">,</span>{"\n"}{"    "}<span class="nt">&#34;experimentalDecorators&#34;</span><span class="p">:</span> <span class="kc">true</span><span class="p">,</span>{"\n"}{"    "}<span class="nt">&#34;noImplicitAny&#34;</span><span class="p">:</span> <span class="kc">true</span><span class="p">,</span>{"\n"}{"    "}<span class="nt">&#34;noImplicitThis&#34;</span><span class="p">:</span> <span class="kc">true</span><span class="p">,</span>{"\n"}{"    "}<span class="nt">&#34;strictNullChecks&#34;</span><span class="p">:</span> <span class="kc">true</span><span class="p">,</span>{"\n"}{"    "}<span class="nt">&#34;removeComments&#34;</span><span class="p">:</span> <span class="kc">true</span><span class="p">,</span>{"\n"}{"    "}<span class="nt">&#34;suppressImplicitAnyIndexErrors&#34;</span><span class="p">:</span> <span class="kc">true</span><span class="p">,</span>{"\n"}{"    "}<span class="nt">&#34;allowSyntheticDefaultImports&#34;</span><span class="p">:</span> <span class="kc">true</span>{"\n"}{"  "}<span class="p">{"}"},</span>{"\n"}{"  "}<span class="nt">&#34;include&#34;</span><span class="p">:</span> <span class="p">[</span>{"\n"}{"    "}<span class="s2">&#34;./**/*.ts&#34;</span>{"\n"}{"  "}<span class="p">],</span>{"\n"}{"  "}<span class="nt">&#34;exclude&#34;</span><span class="p">:</span> <span class="p">[</span>{"\n"}{"    "}<span class="s2">&#34;node_modules&#34;</span><span class="p">,</span>{"\n"}{"    "}<span class="s2">&#34;tools&#34;</span>{"\n"}{"  "}<span class="p">],</span>{"\n"}{"  "}<span class="nt">&#34;compileOnSave&#34;</span><span class="p">:</span> <span class="kc">false</span>{"\n"}<span class="p">{"}"}</span>{"\n"}
        </code>
      </pre>
    )
  }
}
